trigger:
- main
 
pool:
  name: MVCAgent
  demands:
  - agent.os -equals Windows_NT
 
variables:
  buildConfiguration: 'Release'
  solution: 'C:/Centennial/Winter 2025/COMP367_002_DevOps/Lab Assignments/MVC Agile Process with Agile/MVC Agile Process with Agile.sln'
  projects: 'C:/Centennial/Winter 2025/COMP367_002_DevOps/Lab Assignments/MVC Agile Process with Agile/MVC Agile Process with Agile/MVC Agile Process with Agile.csproj'
 
steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    version: '8.x'
 
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '$(projects)'
 
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
 
- task: DotNetCoreCLI@2
  displayName: 'Publish web app'
  inputs:
    command: 'publish'
    projects: '$(projects)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
 
- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'webapp'
    publishLocation: 'pipeline'